### ISSUE TITLE
Most of time cou unable to complete nova-compute upgrade because `ceilometer-agent-compute` is down after upgrade

### ISSUE THREAD

**Issue by valexby** [canonical/charmed-openstack-upgrader#427] opened 2024-05-30 13:59 UTC
Hi,

Because of the known bug [LP1947585](https://bugs.launchpad.net/charm-ceilometer-agent/+bug/1947585) `ceilometer-agent-compute` might be down in many cases after nova-compute release upgrade. Cou fails to complete upgrade in such a case, as the final juju `resume` action fails.

Given that the bugfix for nova-compute wasn't back-ported to Ussuri-Wallaby and the nova bug hasn't had any activity for a year, maybe we could make cou starting `ceilometer-agent` after the nova release upgrade if it is down. That is a natural thing to do for a human-operator upgrading a cloud.

**Comment by jneo8** [comment] 2024-05-31 08:37
Base on [LP1947585](https://bugs.launchpad.net/charm-ceilometer-agent/+bug/1947585), the workaround solution is `sudo systemctl restart ceilometer-agent` is it's not active.

**Comment by Pjack** [comment] 2024-05-31 08:38
Comment from @valexby 

> Without this one fixed on cou side or backported on nova-compute side, managed solutions will face this issue about ~500 nodes * 4 openstack releases = ~ 2000 times  during future upgrades

**Comment by aieri** [comment] 2024-06-06 04:35
it looks to me like [LP#1947585](https://bugs.launchpad.net/charm-ceilometer-agent/+bug/1947585) was backported [all the way back to ussuri](https://review.opendev.org/c/openstack/charm-nova-compute/+/890666), but somehow the fix isn't working for older releases. I think we should just add the workaround within COU.

**Comment by jneo8** [comment] 2024-06-07 09:11
[Discuss for implementation]

There is a limitation in implementation: **How can I know there is a ceilometer-agent unit relate to nova-compute as a subordinate in COU?**

The subordinate information is missing ]when we transform the origin juju status data into COU's Application class](https://github.com/canonical/charmed-openstack-upgrader/blob/b38da2799481aaf12e67e85c3bc9f17f8b85a686/cou/utils/juju_utils.py#L386). This create a awkward situation that I am not able to confirm if the ceilometer-agent unit is there in the same machine.

There will be two options:

1. We follow [LP1947585](https://bugs.launchpad.net/charm-ceilometer-agent/+bug/1947585)'s implementation. We put this restart service logic in the nova-compute application's post-upgrade step. But before that we need to put the subordinate information into COU's application class.
2. We create a new application for ceilometer-agent and include this subordinate application's upgrade step into hypervisor.

Now I prefer option 1 because:
- option 1 follow the behavior in the charm(restart service in nova-compute), see [fix on nova-compute](https://review.opendev.org/c/openstack/charm-nova-compute/+/833886)
- option 2 has a lot of difficulties to overcome. Now the hypervisor still can't handle the subordinate application because of missing machine information in juju status data. This require some refactor in hypervisor step first.

Any feedback is welcome. I would start the implementation next Tuesday(6/11)

**Comment by samuelallan72** [comment] 2024-07-11 01:46
I observed this issue in testing on 2024-07-04 with latest/edge at the time.  

```
Running cloud upgrade...
Verify that all OpenStack applications are in idle state ✔
Back up MySQL databases ✔
Archive old database data on nova-cloud-controller ✔
Resume the unit: 'nova-compute/0' \2024-07-04 01:08:38 [ERROR] action <Action entity_id="568"> failed
Resume the unit: 'nova-compute/2' ✖                                                                                                                                                                                                                                                                                                                         2024-07-04 01:09:08 [ERROR] The following substeps of 'Upgrade plan for units: nova-compute/0, nova-compute/2' failed                                                                                                                                                                                                                                       Upgrade plan for unit 'nova-compute/0': ActionFailed('Run of action \'resume\' with parameters \'<not-set>\' on \'nova-compute/0\' failed with \'Action resume failed: Couldn\'t resume: ceilometer-agent-compute didn\'t resume cleanly.; Services not running that should be: ceilometer-agent-compute\' (id=568 status=failed enqueued=2024-07-04T01:08:13Z started=2024-07-04T01:08:29Z completed=2024-07-04T01:08:38Z output={\'model-uuid\': \'a598a98e-eb7f-4103-8999-7963a979d501\', \'id\': \'568\', \'receiver\': \'nova-compute/0\', \'name\': \'resume\', \'status\': \'failed\', \'message\': "Action resume failed: Couldn\'t resume: ceilometer-agent-compute didn\'t resume cleanly.; Services not running that should be: ceilometer-agent-compute", \'enqueued\': \'2024-07-04T01:08:13Z\', \'started\': \'2024-07-04T01:08:29Z\', \'completed\': \'2024-07-04T01:08:38Z\'})')
2024-07-04 01:09:08 [ERROR] See the known issues at https://canonical-charmed-openstack-upgrader.readthedocs-hosted.com/en/stable/reference/known-issues/
```

**Comment by samuelallan72** [comment] 2024-07-11 04:14
I observed it again with latest/edge today.  I think the problem is in the order of actions.  Here's the plan for a zone of nova-compute:

```
                Upgrade plan for [nova-compute/0, nova-compute/2] in 'zone1' to 'wallaby'
                        Disable nova-compute scheduler from unit: 'nova-compute/0'
                        Disable nova-compute scheduler from unit: 'nova-compute/2'
                        Upgrade software packages of 'nova-compute' from the current APT repositories
                                Ψ Upgrade software packages on unit 'nova-compute/0'
                                Ψ Upgrade software packages on unit 'nova-compute/2'
                        Upgrade 'nova-compute' from 'victoria/stable' to the new channel: 'wallaby/stable'
                        Change charm config of 'nova-compute' 'openstack-origin' to 'cloud:focal-wallaby'
                        Upgrade plan for units: nova-compute/0, nova-compute/2
                                Ψ Upgrade plan for unit 'nova-compute/0'
                                        Pause the unit: 'nova-compute/0'
                                        Upgrade the unit: 'nova-compute/0'
                                        Resume the unit: 'nova-compute/0'
                                Ψ Upgrade plan for unit 'nova-compute/2'
                                        Pause the unit: 'nova-compute/2'
                                        Upgrade the unit: 'nova-compute/2'
                                        Resume the unit: 'nova-compute/2'
                        Enable nova-compute scheduler from unit: 'nova-compute/0'
                        Enable nova-compute scheduler from unit: 'nova-compute/2'
                        Restart service ceilometer-agent-compute for subordinate unit: 'ceilometer-agent/4'
                        Restart service ceilometer-agent-compute for subordinate unit: 'ceilometer-agent/1'
                        Wait for up to 2400s for model 'openstack' to reach the idle state
                        Verify that the workload of 'nova-compute' has been upgraded on units: nova-compute/0, nova-compute/2
```
Note that restarting the service happens after the resume action.  It needs to happen _before_ resuming, because it's the resuming action that fails when ceilometer-agent-compute is not running.

**Comment by samuelallan72** [comment] 2024-07-11 06:23
We discussed this and it appears it could be a race condition inside the nova-compute charm itself, in the resume action.  It seems that ceilometer-agent-compute must be started after nova-compute is resumed, because ceilometer-agent-compute  depends on nova-compute running.  So it seems it must be fixed inside the charm.

A workaround in cou could be:

- resume nova-compute, ignoring errors
- restart ceilometer-agent-compute
- resume nova-compute again.

**Comment by samuelallan72** [comment] 2024-07-15 05:45
Current work around (in this example, nova-compute/0 had subordinitae ceilometer-agent/4, and nova-compute/0 hit this bug):

```
juju ssh ceilometer-agent/4 -- sudo systemctl start ceilometer-agent-compute
# force update status instead of waiting for the next update-status hook
juju exec -u nova-compute/0 -- hooks/update-status
juju exec -u ceilometer-agent/4 -- hooks/update-status

# re-run cou upgrade
cou upgrade --auto-approve --force
```

**Comment by samuelallan72** [comment] 2024-07-17 06:59
> Given that the bugfix for nova-compute wasn't back-ported to Ussuri-Wallaby

I checked and it was indeed backported.  For example, here is the merged patch to wallaby: https://review.opendev.org/c/openstack/charm-nova-compute/+/890664 , and I can verify the code is there in the charm from `juju download nova-compute --channel wallaby/stable`.

So perhaps backported fix didn't fix it in the end? :thinking:

**Comment by jneo8** [comment] 2024-07-17 08:36
The possible workaround in cou could be, override the `_get_resume_unit_step` and `_get_unit_upgrade_steps` in nova-compute o7k app class:

The steps should be: 

```
[
...
{original upgrade step}
...
Run resume action
Restart subordinate services
Run resume again
]
```

**Closed** 2024-07-23 23:12 UTC
