### ISSUE TITLE
Fix the ActionFailed exception 

### ISSUE THREAD

**Issue by gabrielcocenza** [canonical/charmed-openstack-upgrader#386] opened 2024-04-22 21:40 UTC
For some unknown reason, the action to run the upgrade in one of the nova-compute units failed with time out. During the exception handling another exception happened like the logs bellow show:
 
```
2024-04-22 21:22:54 [cou.steps.execute] [INFO] Running: ├── Upgrade the unit: 'nova-compute/0'
2024-04-22 21:22:54 [cou.steps] [DEBUG] running step: UnitUpgradeStep(├── Upgrade the unit: 'nova-compute/0')
2024-04-22 21:24:46 [cou.utils.juju_utils] [INFO] function _get_waited_action_object failed [0]
Traceback (most recent call last):
  File "/home/ubuntu/charmed-openstack-upgrader-1/cou/utils/juju_utils.py", line 116, in wrapper
    return await func(*args, **kwargs)
  File "/home/ubuntu/charmed-openstack-upgrader-1/cou/utils/juju_utils.py", line 257, in _get_waited_action_object
    raise ActionFailed(action, output=action_obj.data)
  File "/home/ubuntu/charmed-openstack-upgrader-1/cou/exceptions.py", line 102, in __init__
    params[key] = getattr(action, key, "<not-set>")
  File "/home/ubuntu/charmed-openstack-upgrader-1/.venv/lib/python3.10/site-packages/juju/model.py", line 287, in __getattr__
    return self.safe_data[name]
KeyError: 'parameters'
2024-04-22 21:24:47 [cou.cli] [ERROR] The following substeps of 'Upgrade plan for units: nova-compute/0' failed
Upgrade plan for unit 'nova-compute/0': TimeoutException('function _get_waited_action_object timed out after 10s')
```

**Comment by aieri** [comment] 2024-05-16 14:40
This seems to be caused by https://github.com/juju/python-libjuju/issues/1048, closing

**Closed by aieri** 2024-05-16 14:40 UTC
