### ISSUE TITLE
COU should use source more than `currento_os_release` to verify that app was upgraded

### ISSUE THREAD

**Issue by rgildein** [canonical/charmed-openstack-upgrader#158] opened 2023-11-01 15:50 UTC
After successful upgrade from ussuri to victoria, I saw following message.
```bash
WARNING: Please upgrade manually the data plane apps: nova-compute, ceph-osd 
```
What is the right behavior, but after the manual upgrading of all the nova-compute units, the message will even disappear even when cepph-osd was not upgraded. The issue is that ceph-osd is on the same machine and currento_os_release returns that it is already victoria.

**Comment by gabrielcocenza** [comment] 2023-11-16 09:51
The problem is that the workload version of octopus is compatible with ussuri and victoria. If all applications already upgraded to victoria, than ceph-osd won't generate a plan to change `source`.

Base on our discussion. we came in the conclusion that this is a corner case and when the application really needs to upgrade the workload version the plan will generate a plan as expected even if ceph-osd is the application that remains in the cloud to be upgraded.

Closing this issue

**Closed by gabrielcocenza** 2023-11-16 09:51 UTC
Labels: bug, medium
