### ISSUE TITLE
Remove protobuf pinning

### ISSUE THREAD

**Issue by gabrielcocenza** [canonical/charmed-openstack-upgrader#193] opened 2023-12-08 13:47 UTC
This is a reminder to remove the protobuf pinning that happened on #192 once the upstream issue is solved

**Comment by agileshaw** [comment] 2023-12-13 16:00
The issue is fixed in https://github.com/go-macaroon-bakery/py-macaroon-bakery/pull/95. We can remove the pin now.

**Closed** 2023-12-13 23:53 UTC
